project_id = "uidwcgxbybjpbteowrnh"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.create-one-time-payment]
verify_jwt = false

[functions.claim-onboarding-row]
verify_jwt = false