// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uidwcgxbybjpbteowrnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZHdjZ3hieWJqcGJ0ZW93cm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NDg5MTQsImV4cCI6MjA4NDMyNDkxNH0.bC-IKmrzZbj_AXcReSWO9GjnmWmp_v3NP3tOo90PnZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});